name: Spelling Internalization
on:
  pull_request:
    paths:
    - 'test.js'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch commit
        uses: actions/checkout@v2
        
      - name: check spelling
        uses: UnicornGlobal/spellcheck-github-actions@master
